# Generated by Django 3.2.8 on 2021-11-11 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
    ]
